### ISSUE TITLE
Add bundle of joy menu screen at startup, and with transparent UI (similar to hangouts)

### ISSUE THREAD

**Issue by bobnomercy** [Chromenomercy/bundle-of-joy#24]

**Comment by Chromadude** [comment]
We can't make the window itself transparent but we could possibly use a screenshot of the background windows? Problem would be updating it. We wouldn't know when the background changes and it is too laggy taking screenshots every frame

**Comment by bobnomercy** [comment]
fixed issued with window placement

**Comment by Chromadude** [comment]
What do you mean?

**Comment by Chromadude** [comment]
Oh you mean you made menu window centered. ok
