### ISSUE TITLE
More advanced tutorial game

### ISSUE THREAD

**Issue by bobnomercy** [Chromenomercy/bundle-of-joy#37]

**Comment by Chromadude** [comment]
this is called pong. @bobnomercy should this be closed now?

**Comment by Chromadude** [comment]
@bobnomercy Since I have finished the required work on QAC, Pong should be updated to make use of the features. We should be able to release v1.1.0 once that is done tomorrow!

**Comment by bobnomercy** [comment]
Fantastic, will do tomorrow
