### ISSUE TITLE
Image and text management without pygame in QAC

### ISSUE THREAD

**Issue by bobnomercy** [Chromenomercy/bundle-of-joy#41]
We've got to make a nicer way of storing images using QAC

**Comment by bobnomercy** [comment]
We can't use images because the video system is not initialised

**Comment by bobnomercy** [comment]
pygame.error: No video mode has been set

**Comment by Chromadude** [comment]
Image management done but could be better

**Comment by Chromadude** [comment]
Added simple text. See Issue #39
