### ISSUE TITLE
allow tuples to be given instead of x, y as separate attributes

### ISSUE THREAD

**Issue by bobnomercy** [Chromenomercy/bundle-of-joy#72]
This is done in pygame  must be possible. Do this for all attributes (maybe args or kwargs)

**Comment by Chromadude** [comment]
pygame uses C so and that might make it easier. I could still do it but it would involve a lot of messy type checks and when an init already takes lots of args and kwargs it could get even messy. Should I still do it or can we just leave it the way it is?

**Comment by bobnomercy** [comment]
Have a go at it, it will be nice to see how if works

**Comment by Chromadude** [comment]
Ok I have decided not to as it is not worth the time. Instead I have made all parameters be in position, size form since then they will be easy to use whether we are using lists/tuples or not
